### ISSUE TITLE
graphics

### ISSUE THREAD

**Issue by leraved** [leraved/prog_Vedernikova#6]
@Antosha417, графика
https://github.com/leraved/prog_Vedernikova/commit/c0e05214f7e35efa351e80acac3fc716392b60ac#diff-ac3e3060afa0c85bc86f9001d02bede2

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by antosha417** [comment]
Давай хорошо подумаем над названиями переменных. Почему у тебя цифры в названиях? Это не намекает тебе на то, что нужно использовать списки и циклы?

**Comment by antosha417** [comment]
Очень много одинаковых строк кода (в народе копипасты) перепиши через циклы

**Comment by antosha417** [comment]
забыла в конце написать 
```
window.getMouse()
window.close()
```
программа сразу закрывается, не видно картинку

**Comment by antosha417** [comment]
Пока ставлю тебе 0,6  за задачу, чтобы поднять поправь код.

**Comment by leraved** [comment]
у меня проблемы с облаками. там круги разных радиусов, и нет четкого смещения. это как-то можно задать циклами?

**Comment by antosha417** [comment]
Сейчас скажу

**Comment by antosha417** [comment]
https://github.com/konovalovatanya26/prog_Konovalova/issues/9#issuecomment-439221063

**Comment by antosha417** [comment]
На будущее пиши лучше в чат, там быстрее отвечу

**Comment by leraved** [comment]
@antosha417, задала облака рандомом
https://github.com/leraved/prog_Vedernikova/commit/6e32b4e5e1839d4e268f9398136ec404a9798aa7#diff-ac3e3060afa0c85bc86f9001d02bede2

**Comment by antosha417** [comment]
`distance_x` было бы лучше, я думаю.
Закрывай issue
